/* eslint-disable sonarjs/no-duplicate-string */

export const mockGetClientAccountAttributeService = [
  {
    ClientAttributeId: 6,
    ClientAccountAttributeRequired: true,
    ClientAccountAttributeActiveFlag: true,
    ClientAccountAttributeUnique: false,
    EntityState: 0,
  },
  {
    ClientAttributeId: 5,
    ClientAccountAttributeRequired: false,
    ClientAccountAttributeActiveFlag: false,
    ClientAccountAttributeUnique: false,
    EntityState: 0,
  },
]

export const mockGetClientService = [
  {
    ObjectTypeInternalCode: 1,
    ClientId: 68,
    ClientFirstName: 'Amaro',
    ClientLastName: 'Silva',
    Value: '3515381024',
    ClientAttributeItemId: 0,
    ClientAttributeId: 4,
    ClientModifiedByUserId: 0,
    UserId: 0,
    ClientActiveFlag: false,
    ClientModifiedDate: '0001-01-01T00:00:00',
    AccountTypeId: 0,
    ClientObservation: '',
    OpenCases: 0,
    ClientLogId: 0,
    EntityState: 0,
  },
  {
    ObjectTypeInternalCode: 3,
    ClientId: 68,
    ClientFirstName: 'Amaro',
    ClientLastName: 'Silva',
    Value: 'True',
    ClientAttributeItemId: 0,
    ClientAttributeId: 38,
    ClientModifiedByUserId: 0,
    UserId: 0,
    ClientActiveFlag: false,
    ClientModifiedDate: '0001-01-01T00:00:00',
    AccountTypeId: 0,
    ClientObservation: '',
    OpenCases: 0,
    ClientLogId: 0,
    EntityState: 0,
  },
  {
    ObjectTypeInternalCode: 3,
    ClientId: 68,
    ClientFirstName: 'Amaro',
    ClientLastName: 'Silva',
    Value: 'True',
    ClientAttributeItemId: 0,
    ClientAttributeId: 39,
    ClientModifiedByUserId: 0,
    UserId: 0,
    ClientActiveFlag: false,
    ClientModifiedDate: '0001-01-01T00:00:00',
    AccountTypeId: 0,
    ClientObservation: '',
    OpenCases: 0,
    ClientLogId: 0,
    EntityState: 0,
  },
]

export const mockSearchUserChannelByUserChannelIdService = [
  {
    SCInternalCodeUser: 3,
    AccountDetailDescrip: null,
    GroupAccountDetailByParamsBE: null,
    TextBody: null,
    TextSubject: null,
    MessageTW: false,
    UserChannelId: 2805,
    SourceUserChannelId: 9364,
    UCName: 'Amaro Silva',
    UCUserName: 'Amaro Silva',
    ClientId: 68,
    ServiceChannelId: 4,
    UCCreated: '2019-02-07T15:43:58.623',
    UCPublicationTo: '1579771178768282',
    ServiceChannelIdUser: 0,
    SCName: 'Facebook',
    SCImage:
      'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAALNJREFUOE9joAow8204bOXX9J8UDNID1c7A4BI7+79H0mKSMEgPVDsDAzYFMByWu+r/sXOP/v/6/ef/+4/f/9+4+xouB9WO34D9J+79RwcwOah2/AZ8/fYTrCm/bgnc/zA5qHb8BsCAS+wsDDmoduwG4AKPn3+Eq4FqJ82AJeuOw9VAtWM3AOZfGIDxHSImwdVAtRMXBtjkoNqHhQGuCQsOY1MAwjCALu6esOgIVDslgIEBABdZ+usDSwaxAAAAAElFTkSuQmCC',
    ClientIdOld: null,
    AccountId: 0,
    ModifiedByUserId: 0,
    UCPublicationToAccount: '1579771178768282',
    UCUserNameOriginal: null,
    SourceUserId: null,
    Client: null,
    Selected: false,
    EntityState: 0,
  },
]

export const mockSearchUserChannelByClientIdService = [
  {
    SCInternalCodeUser: 3,
    AccountDetailDescrip: null,
    GroupAccountDetailByParamsBE: null,
    TextBody: null,
    TextSubject: null,
    MessageTW: false,
    UserChannelId: 2805,
    SourceUserChannelId: 9364,
    UCName: 'Amaro Silva',
    UCUserName: 'Amaro Silva',
    ClientId: 68,
    ServiceChannelId: 4,
    UCCreated: '2019-02-07T15:43:58.623',
    UCPublicationTo: '1579771178768282',
    ServiceChannelIdUser: 0,
    SCName: 'Facebook',
    SCImage:
      'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAALNJREFUOE9joAow8204bOXX9J8UDNID1c7A4BI7+79H0mKSMEgPVDsDAzYFMByWu+r/sXOP/v/6/ef/+4/f/9+4+xouB9WO34D9J+79RwcwOah2/AZ8/fYTrCm/bgnc/zA5qHb8BsCAS+wsDDmoduwG4AKPn3+Eq4FqJ82AJeuOw9VAtWM3AOZfGIDxHSImwdVAtRMXBtjkoNqHhQGuCQsOY1MAwjCALu6esOgIVDslgIEBABdZ+usDSwaxAAAAAElFTkSuQmCC',
    ClientIdOld: null,
    AccountId: 0,
    ModifiedByUserId: 0,
    UCPublicationToAccount: '1579771178768282',
    UCUserNameOriginal: null,
    SourceUserId: null,
    Client: null,
    Selected: false,
    EntityState: 0,
  },
  {
    SCInternalCodeUser: 7,
    AccountDetailDescrip: null,
    GroupAccountDetailByParamsBE: null,
    TextBody: null,
    TextSubject: null,
    MessageTW: false,
    UserChannelId: 96,
    SourceUserChannelId: 54,
    UCName: '3624000000',
    UCUserName: '3624000000',
    ClientId: 68,
    ServiceChannelId: 8,
    UCCreated: '2016-10-18T16:15:10.547',
    UCPublicationTo: '3624000000',
    ServiceChannelIdUser: 0,
    SCName: 'Email',
    SCImage: null,
    ClientIdOld: null,
    AccountId: 0,
    ModifiedByUserId: 0,
    UCPublicationToAccount: null,
    UCUserNameOriginal: null,
    SourceUserId: null,
    Client: null,
    Selected: false,
    EntityState: 0,
  },
]
